package br.com.gamoravet.app;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.os.*;
import android.security.keystore.KeyGenParameterSpec;
import android.security.keystore.KeyProperties;
import android.util.Base64;
import android.webkit.*;
import org.json.JSONObject;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.security.KeyStore;
import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.crypto.spec.GCMParameterSpec;

public class MainActivity extends Activity {
 private WebView webView; private String pendingAuthUrl;
 @Override protected void onCreate(Bundle b){super.onCreate(b);createNotificationChannel();requestNotificationPermission();captureAuthIntent(getIntent());webView=new WebView(this);setContentView(webView);WebSettings s=webView.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(true);s.setAllowContentAccess(true);s.setDatabaseEnabled(true);s.setLoadsImagesAutomatically(true);s.setJavaScriptCanOpenWindowsAutomatically(false);s.setCacheMode(WebSettings.LOAD_NO_CACHE);webView.clearCache(true);webView.clearHistory();webView.addJavascriptInterface(new GamoraVetBridge(this),"GamoraVetAndroid");webView.setWebViewClient(new WebViewClient(){@Override public void onPageFinished(WebView v,String url){super.onPageFinished(v,url);if(url!=null&&url.endsWith("index.html")){v.evaluateJavascript("(function(){var v='126';function add(src,next){var s=document.createElement('script');s.src=src+'?v='+v;s.onload=next||function(){};document.body.appendChild(s)}add('medications-enhancement.js',function(){add('medication-history-fix.js',function(){add('consultations-enhancement.js',function(){add('history-enhancement.js',function(){add('consultations-reschedule.js',function(){add('sharing-lgpd-enhancement.js',function(){add('auth-lgpd-enhancement.js',function(){add('auth-real-1.2.js',function(){add('pets-backend-1.2.js',function(){window.__GAMORAVET_ENHANCED__=true})})})})})})})})})})();",null);v.postDelayed(MainActivity.this::deliverPendingAuthUrl,600);}}});webView.setWebChromeClient(new WebChromeClient());webView.loadUrl("file:///android_asset/index.html");}
 @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);captureAuthIntent(i);if(webView!=null)webView.postDelayed(this::deliverPendingAuthUrl,300);}private void captureAuthIntent(Intent i){if(i!=null&&Intent.ACTION_VIEW.equals(i.getAction())&&i.getData()!=null)pendingAuthUrl=i.getData().toString();}private void deliverPendingAuthUrl(){if(webView==null||pendingAuthUrl==null)return;String u=JSONObject.quote(pendingAuthUrl);pendingAuthUrl=null;webView.evaluateJavascript("window.GamoraVetAuth12&&window.GamoraVetAuth12.handleDeepLink("+u+");",null);}
 private void createNotificationChannel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel(NotificationReceiver.CHANNEL_ID,"Lembretes GamoraVet",NotificationManager.IMPORTANCE_HIGH);c.setDescription("Consultas, exames, vacinas, medicamentos e outros cuidados agendados");getSystemService(NotificationManager.class).createNotificationChannel(c);}}private void requestNotificationPermission(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},1001);}
 public static class GamoraVetBridge{
  private static final String KS="AndroidKeyStore",ALIAS="GamoraVetSessionKeyV1",PREF="gamoravet_secure_session",FIELD="session";private final MainActivity a;GamoraVetBridge(MainActivity a){this.a=a;}
  @JavascriptInterface public boolean notificationsAvailable(){return Build.VERSION.SDK_INT<33||a.checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)==PackageManager.PERMISSION_GRANTED;}
  @JavascriptInterface public void scheduleNotification(int id,long ts,String title,String text){if(ts<=System.currentTimeMillis())return;Intent i=new Intent(a,NotificationReceiver.class);i.putExtra("id",id);i.putExtra("title",title);i.putExtra("text",text);PendingIntent p=PendingIntent.getBroadcast(a,id,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);AlarmManager am=(AlarmManager)a.getSystemService(Context.ALARM_SERVICE);if(title!=null&&title.toLowerCase().contains("medicamento"))am.setRepeating(AlarmManager.RTC_WAKEUP,ts,AlarmManager.INTERVAL_DAY,p);else am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,ts,p);}
  @JavascriptInterface public void cancelNotification(int id){Intent i=new Intent(a,NotificationReceiver.class);PendingIntent p=PendingIntent.getBroadcast(a,id,i,PendingIntent.FLAG_NO_CREATE|PendingIntent.FLAG_IMMUTABLE);if(p!=null){((AlarmManager)a.getSystemService(Context.ALARM_SERVICE)).cancel(p);p.cancel();}}@JavascriptInterface public void closeApp(){a.runOnUiThread(a::finish);}@JavascriptInterface public boolean supabaseConfigured(){return !BuildConfig.SUPABASE_URL.isEmpty()&&!BuildConfig.SUPABASE_PUBLISHABLE_KEY.isEmpty();}@JavascriptInterface public boolean hasSecureSession(){try{return loadSecureSession()!=null;}catch(Exception e){return false;}}
  @JavascriptInterface public void restoreSession(String id){new Thread(()->{int st=0;String body="";try{JSONObject saved=loadSecureSession();if(saved==null)throw new IllegalStateException("Sessão não encontrada.");Result r=request("POST","/auth/v1/token?grant_type=refresh_token",new JSONObject().put("refresh_token",saved.getString("refresh_token")),null,null);st=r.status;body=r.body;if(st>=200&&st<300)saveSecureSession(new JSONObject(body));else clearSecureSession();}catch(Exception e){clearSecureSession();body=error(e);}callback(id,st,body);}).start();}
  @JavascriptInterface public void clearSecureSession(){a.getSharedPreferences(PREF,Context.MODE_PRIVATE).edit().remove(FIELD).apply();}
  @JavascriptInterface public void authRequest(String id,String action,String json){new Thread(()->performAuth(id,action,json)).start();}
  @JavascriptInterface public void dataRequest(String id,String action,String json){new Thread(()->performData(id,action,json)).start();}
  private void performData(String id,String action,String json){int st=0;String body="";try{JSONObject sess=loadSecureSession();if(sess==null)throw new IllegalStateException("Faça login novamente.");String token=sess.getString("access_token");JSONObject p=new JSONObject(json==null?"{}":json);Result r;if("listPets".equals(action)){r=request("GET","/rest/v1/pets?select=id,name,species,breed,sex,birth_date,weight_kg,photo_path,created_at&order=created_at.asc",null,token,null);}else if("createPet".equals(action)){JSONObject rpc=new JSONObject().put("p_name",p.getString("name")).put("p_species",nullable(p,"species")).put("p_breed",nullable(p,"breed")).put("p_sex",nullable(p,"sex")).put("p_birth_date",nullable(p,"birth_date")).put("p_weight_kg",p.has("weight_kg")&&!p.isNull("weight_kg")?p.getDouble("weight_kg"):JSONObject.NULL).put("p_photo_path",JSONObject.NULL);r=request("POST","/rest/v1/rpc/create_pet_with_guardian",rpc,token,null);}else if("updatePet".equals(action)){String petId=p.getString("id");JSONObject patch=new JSONObject().put("name",p.getString("name")).put("species",nullable(p,"species")).put("breed",nullable(p,"breed")).put("weight_kg",p.has("weight_kg")&&!p.isNull("weight_kg")?p.getDouble("weight_kg"):JSONObject.NULL);r=request("PATCH","/rest/v1/pets?id=eq."+URLEncoder.encode(petId,"UTF-8"),patch,token,"return=representation");}else throw new IllegalArgumentException("Operação de dados inválida.");st=r.status;body=r.body;}catch(Exception e){body=error(e);}dataCallback(id,st,body);}
  private Object nullable(JSONObject p,String k){String v=p.optString(k,"").trim();return v.isEmpty()?JSONObject.NULL:v;}
  private void performAuth(String id,String action,String json){int st=0;String body="";try{if(!supabaseConfigured())throw new IllegalStateException("Configuração do servidor indisponível nesta compilação.");JSONObject p=new JSONObject(json==null?"{}":json);String ep,m="POST";JSONObject q=new JSONObject();if("signup".equals(action)){ep="/auth/v1/signup?redirect_to="+URLEncoder.encode("gamoravet://auth/callback","UTF-8");q.put("email",p.getString("email")).put("password",p.getString("password")).put("data",new JSONObject().put("full_name",p.optString("full_name","")).put("role",p.optString("role","tutor")));}else if("login".equals(action)){ep="/auth/v1/token?grant_type=password";q.put("email",p.getString("email")).put("password",p.getString("password"));}else if("recover".equals(action)){ep="/auth/v1/recover?redirect_to="+URLEncoder.encode("gamoravet://auth/callback","UTF-8");q.put("email",p.getString("email"));}else if("refresh".equals(action)){ep="/auth/v1/token?grant_type=refresh_token";q.put("refresh_token",p.getString("refresh_token"));}else if("updatePassword".equals(action)){ep="/auth/v1/user";m="PUT";q.put("password",p.getString("password"));}else throw new IllegalArgumentException("Ação de autenticação inválida.");Result r=request(m,ep,q,p.optString("access_token",null),null);st=r.status;body=r.body;if(("login".equals(action)||"refresh".equals(action))&&st>=200&&st<300)saveSecureSession(new JSONObject(body));}catch(Exception e){body=error(e);}callback(id,st,body);}
  private Result request(String method,String endpoint,JSONObject payload,String access,String prefer)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(BuildConfig.SUPABASE_URL+endpoint).openConnection();c.setRequestMethod(method);c.setConnectTimeout(15000);c.setReadTimeout(20000);c.setRequestProperty("apikey",BuildConfig.SUPABASE_PUBLISHABLE_KEY);c.setRequestProperty("Content-Type","application/json");if(access!=null&&!access.isEmpty())c.setRequestProperty("Authorization","Bearer "+access);if(prefer!=null)c.setRequestProperty("Prefer",prefer);if(payload!=null){c.setDoOutput(true);try(OutputStream os=c.getOutputStream()){os.write(payload.toString().getBytes(StandardCharsets.UTF_8));}}int st=c.getResponseCode();InputStream is=st>=200&&st<300?c.getInputStream():c.getErrorStream();String body=readAll(is);c.disconnect();return new Result(st,body);}
  private SecretKey key()throws Exception{KeyStore s=KeyStore.getInstance(KS);s.load(null);if(!s.containsAlias(ALIAS)){KeyGenerator kg=KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES,KS);kg.init(new KeyGenParameterSpec.Builder(ALIAS,KeyProperties.PURPOSE_ENCRYPT|KeyProperties.PURPOSE_DECRYPT).setBlockModes(KeyProperties.BLOCK_MODE_GCM).setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE).setRandomizedEncryptionRequired(true).build());kg.generateKey();}return((KeyStore.SecretKeyEntry)s.getEntry(ALIAS,null)).getSecretKey();}
  private void saveSecureSession(JSONObject auth)throws Exception{String at=auth.optString("access_token",""),rt=auth.optString("refresh_token","");if(at.isEmpty()||rt.isEmpty())return;JSONObject s=new JSONObject().put("access_token",at).put("refresh_token",rt).put("user",auth.optJSONObject("user"));Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.ENCRYPT_MODE,key());byte[] enc=c.doFinal(s.toString().getBytes(StandardCharsets.UTF_8));a.getSharedPreferences(PREF,Context.MODE_PRIVATE).edit().putString(FIELD,Base64.encodeToString(c.getIV(),Base64.NO_WRAP)+"."+Base64.encodeToString(enc,Base64.NO_WRAP)).apply();}
  private JSONObject loadSecureSession()throws Exception{String p=a.getSharedPreferences(PREF,Context.MODE_PRIVATE).getString(FIELD,null);if(p==null)return null;String[] x=p.split("\\.",2);Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.DECRYPT_MODE,key(),new GCMParameterSpec(128,Base64.decode(x[0],Base64.NO_WRAP)));return new JSONObject(new String(c.doFinal(Base64.decode(x[1],Base64.NO_WRAP)),StandardCharsets.UTF_8));}
  private String readAll(InputStream is)throws IOException{if(is==null)return"";BufferedReader r=new BufferedReader(new InputStreamReader(is,StandardCharsets.UTF_8));StringBuilder b=new StringBuilder();String l;while((l=r.readLine())!=null)b.append(l);return b.toString();}private String error(Exception e){try{return new JSONObject().put("message",e.getMessage()==null?"Falha de comunicação.":e.getMessage()).toString();}catch(Exception x){return"{\"message\":\"Falha de comunicação.\"}";}}
  private void callback(String id,int st,String body){String js="window.GamoraVetAuth12&&window.GamoraVetAuth12.onNativeResult("+JSONObject.quote(id)+","+st+","+JSONObject.quote(body)+");";a.runOnUiThread(()->a.webView.evaluateJavascript(js,null));}private void dataCallback(String id,int st,String body){String js="window.GamoraVetPets12&&window.GamoraVetPets12.onNativeResult("+JSONObject.quote(id)+","+st+","+JSONObject.quote(body)+");";a.runOnUiThread(()->a.webView.evaluateJavascript(js,null));}private static class Result{final int status;final String body;Result(int s,String b){status=s;body=b;}}
 }
 @Override public void onBackPressed(){if(webView!=null)webView.evaluateJavascript("if(window.gamoraBack){window.gamoraBack();}else if(window.GamoraVetAndroid){GamoraVetAndroid.closeApp();}",null);else super.onBackPressed();}@Override protected void onDestroy(){if(webView!=null){webView.destroy();webView=null;}super.onDestroy();}
}
