package br.com.gamoravet.app;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.os.*;
import android.provider.Settings;
import android.security.keystore.KeyGenParameterSpec;
import android.security.keystore.KeyProperties;
import android.util.Base64;
import android.webkit.*;
import org.json.JSONObject;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.security.KeyStore;
import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.crypto.spec.GCMParameterSpec;

public class MainActivity extends Activity {
    private WebView webView; private String pendingAuthUrl;
    @Override protected void onCreate(Bundle b){super.onCreate(b);createNotificationChannel();requestNotificationPermission();captureAuthIntent(getIntent());webView=new WebView(this);setContentView(webView);WebSettings s=webView.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(true);s.setAllowContentAccess(true);s.setDatabaseEnabled(true);s.setLoadsImagesAutomatically(true);s.setJavaScriptCanOpenWindowsAutomatically(false);s.setCacheMode(WebSettings.LOAD_NO_CACHE);webView.clearCache(true);webView.clearHistory();webView.addJavascriptInterface(new GamoraVetBridge(this),"GamoraVetAndroid");webView.setWebViewClient(new WebViewClient(){@Override public void onPageFinished(WebView v,String url){super.onPageFinished(v,url);if(url!=null&&url.endsWith("index.html")){v.evaluateJavascript("(function(){var v='123';function add(src,next){var s=document.createElement('script');s.src=src+'?v='+v;s.onload=next||function(){};document.body.appendChild(s)}add('medications-enhancement.js',function(){add('medication-history-fix.js',function(){add('consultations-enhancement.js',function(){add('history-enhancement.js',function(){add('consultations-reschedule.js',function(){add('sharing-lgpd-enhancement.js',function(){add('auth-lgpd-enhancement.js',function(){add('auth-real-1.2.js',function(){window.__GAMORAVET_ENHANCED__=true})})})})})})})})})();",null);v.postDelayed(MainActivity.this::deliverPendingAuthUrl,600);}}});webView.setWebChromeClient(new WebChromeClient());webView.setFocusable(true);webView.setFocusableInTouchMode(true);webView.requestFocus();webView.loadUrl("file:///android_asset/index.html");}
    @Override protected void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent);captureAuthIntent(intent);if(webView!=null)webView.postDelayed(this::deliverPendingAuthUrl,300);}
    private void captureAuthIntent(Intent intent){if(intent!=null&&Intent.ACTION_VIEW.equals(intent.getAction())&&intent.getData()!=null)pendingAuthUrl=intent.getData().toString();}
    private void deliverPendingAuthUrl(){if(webView==null||pendingAuthUrl==null)return;String u=JSONObject.quote(pendingAuthUrl);pendingAuthUrl=null;webView.evaluateJavascript("window.GamoraVetAuth12&&window.GamoraVetAuth12.handleDeepLink("+u+");",null);}
    private void createNotificationChannel(){if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.O){NotificationManager m=getSystemService(NotificationManager.class);NotificationChannel c=new NotificationChannel(NotificationReceiver.CHANNEL_ID,"Lembretes GamoraVet",NotificationManager.IMPORTANCE_HIGH);c.setDescription("Consultas, exames, vacinas, medicamentos e outros cuidados agendados");m.createNotificationChannel(c);}}
    private void requestNotificationPermission(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},1001);}

    public static class GamoraVetBridge{
        private static final String KS="AndroidKeyStore",ALIAS="GamoraVetSessionKeyV1",PREF="gamoravet_secure_session",FIELD="session";private final MainActivity a;GamoraVetBridge(MainActivity a){this.a=a;}
        @JavascriptInterface public boolean notificationsAvailable(){return Build.VERSION.SDK_INT<33||a.checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)==PackageManager.PERMISSION_GRANTED;}
        @JavascriptInterface public void scheduleNotification(int id,long ts,String title,String text){if(ts<=System.currentTimeMillis())return;Intent i=new Intent(a,NotificationReceiver.class);i.putExtra("id",id);i.putExtra("title",title);i.putExtra("text",text);PendingIntent p=PendingIntent.getBroadcast(a,id,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);AlarmManager am=(AlarmManager)a.getSystemService(Context.ALARM_SERVICE);boolean daily=title!=null&&title.toLowerCase().contains("medicamento");if(daily)am.setRepeating(AlarmManager.RTC_WAKEUP,ts,AlarmManager.INTERVAL_DAY,p);else am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,ts,p);}
        @JavascriptInterface public void cancelNotification(int id){Intent i=new Intent(a,NotificationReceiver.class);PendingIntent p=PendingIntent.getBroadcast(a,id,i,PendingIntent.FLAG_NO_CREATE|PendingIntent.FLAG_IMMUTABLE);if(p!=null){AlarmManager am=(AlarmManager)a.getSystemService(Context.ALARM_SERVICE);am.cancel(p);p.cancel();}}
        @JavascriptInterface public void closeApp(){a.runOnUiThread(a::finish);}
        @JavascriptInterface public boolean supabaseConfigured(){return !BuildConfig.SUPABASE_URL.isEmpty()&&!BuildConfig.SUPABASE_PUBLISHABLE_KEY.isEmpty();}
        @JavascriptInterface public boolean hasSecureSession(){try{return loadSecureSession()!=null;}catch(Exception e){return false;}}
        @JavascriptInterface public void restoreSession(String requestId){new Thread(()->{int status=0;String body="";try{JSONObject saved=loadSecureSession();if(saved==null)throw new IllegalStateException("Sessão não encontrada.");String refresh=saved.optString("refresh_token","");if(refresh.isEmpty())throw new IllegalStateException("Sessão sem renovação disponível.");Result r=request("POST","/auth/v1/token?grant_type=refresh_token",new JSONObject().put("refresh_token",refresh),null);status=r.status;body=r.body;if(status>=200&&status<300){JSONObject fresh=new JSONObject(body);saveSecureSession(fresh);}}catch(Exception e){clearSecureSession();body=error(e);}callback(requestId,status,body);}).start();}
        @JavascriptInterface public void clearSecureSession(){a.getSharedPreferences(PREF,Context.MODE_PRIVATE).edit().remove(FIELD).apply();}
        @JavascriptInterface public void authRequest(String requestId,String action,String payloadJson){new Thread(()->performAuth(requestId,action,payloadJson)).start();}
        private void performAuth(String requestId,String action,String payloadJson){int status=0;String body="";try{if(!supabaseConfigured())throw new IllegalStateException("Configuração do servidor indisponível nesta compilação.");JSONObject p=new JSONObject(payloadJson==null?"{}":payloadJson);String endpoint,method="POST";JSONObject payload=new JSONObject();if("signup".equals(action)){endpoint="/auth/v1/signup?redirect_to="+URLEncoder.encode("gamoravet://auth/callback","UTF-8");payload.put("email",p.getString("email"));payload.put("password",p.getString("password"));payload.put("data",new JSONObject().put("full_name",p.optString("full_name","")).put("role",p.optString("role","tutor")));}else if("login".equals(action)){endpoint="/auth/v1/token?grant_type=password";payload.put("email",p.getString("email"));payload.put("password",p.getString("password"));}else if("recover".equals(action)){endpoint="/auth/v1/recover?redirect_to="+URLEncoder.encode("gamoravet://auth/callback","UTF-8");payload.put("email",p.getString("email"));}else if("refresh".equals(action)){endpoint="/auth/v1/token?grant_type=refresh_token";payload.put("refresh_token",p.getString("refresh_token"));}else if("updatePassword".equals(action)){endpoint="/auth/v1/user";method="PUT";payload.put("password",p.getString("password"));}else throw new IllegalArgumentException("Ação de autenticação inválida.");Result r=request(method,endpoint,payload,p.optString("access_token",null));status=r.status;body=r.body;if(("login".equals(action)||"refresh".equals(action))&&status>=200&&status<300)saveSecureSession(new JSONObject(body));}catch(Exception e){body=error(e);}callback(requestId,status,body);}
        private Result request(String method,String endpoint,JSONObject payload,String access)throws Exception{URL url=new URL(BuildConfig.SUPABASE_URL+endpoint);HttpURLConnection c=(HttpURLConnection)url.openConnection();c.setRequestMethod(method);c.setConnectTimeout(15000);c.setReadTimeout(20000);c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");c.setRequestProperty("apikey",BuildConfig.SUPABASE_PUBLISHABLE_KEY);if(access!=null&&!access.isEmpty())c.setRequestProperty("Authorization","Bearer "+access);try(OutputStream os=c.getOutputStream()){os.write(payload.toString().getBytes(StandardCharsets.UTF_8));}int status=c.getResponseCode();InputStream is=status>=200&&status<300?c.getInputStream():c.getErrorStream();String body=readAll(is);c.disconnect();return new Result(status,body);}
        private SecretKey key()throws Exception{KeyStore store=KeyStore.getInstance(KS);store.load(null);if(!store.containsAlias(ALIAS)){KeyGenerator kg=KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES,KS);kg.init(new KeyGenParameterSpec.Builder(ALIAS,KeyProperties.PURPOSE_ENCRYPT|KeyProperties.PURPOSE_DECRYPT).setBlockModes(KeyProperties.BLOCK_MODE_GCM).setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE).setRandomizedEncryptionRequired(true).build());kg.generateKey();}return((KeyStore.SecretKeyEntry)store.getEntry(ALIAS,null)).getSecretKey();}
        private void saveSecureSession(JSONObject auth)throws Exception{String at=auth.optString("access_token",""),rt=auth.optString("refresh_token","");if(at.isEmpty()||rt.isEmpty())return;JSONObject s=new JSONObject().put("access_token",at).put("refresh_token",rt).put("user",auth.optJSONObject("user"));Cipher cipher=Cipher.getInstance("AES/GCM/NoPadding");cipher.init(Cipher.ENCRYPT_MODE,key());byte[] enc=cipher.doFinal(s.toString().getBytes(StandardCharsets.UTF_8));String packed=Base64.encodeToString(cipher.getIV(),Base64.NO_WRAP)+"."+Base64.encodeToString(enc,Base64.NO_WRAP);a.getSharedPreferences(PREF,Context.MODE_PRIVATE).edit().putString(FIELD,packed).apply();}
        private JSONObject loadSecureSession()throws Exception{String packed=a.getSharedPreferences(PREF,Context.MODE_PRIVATE).getString(FIELD,null);if(packed==null)return null;String[] parts=packed.split("\\.",2);if(parts.length!=2)return null;Cipher cipher=Cipher.getInstance("AES/GCM/NoPadding");cipher.init(Cipher.DECRYPT_MODE,key(),new GCMParameterSpec(128,Base64.decode(parts[0],Base64.NO_WRAP)));byte[] plain=cipher.doFinal(Base64.decode(parts[1],Base64.NO_WRAP));return new JSONObject(new String(plain,StandardCharsets.UTF_8));}
        private String readAll(InputStream is)throws IOException{if(is==null)return "";BufferedReader r=new BufferedReader(new InputStreamReader(is,StandardCharsets.UTF_8));StringBuilder b=new StringBuilder();String line;while((line=r.readLine())!=null)b.append(line);return b.toString();}
        private String error(Exception e){try{return new JSONObject().put("message",e.getMessage()==null?"Falha de comunicação.":e.getMessage()).toString();}catch(Exception x){return "{\"message\":\"Falha de comunicação.\"}";}}
        private void callback(String id,int status,String body){String js="window.GamoraVetAuth12&&window.GamoraVetAuth12.onNativeResult("+JSONObject.quote(id)+","+status+","+JSONObject.quote(body)+");";a.runOnUiThread(()->{if(a.webView!=null)a.webView.evaluateJavascript(js,null);});}
        private static class Result{final int status;final String body;Result(int s,String b){status=s;body=b;}}
    }
    @Override public void onBackPressed(){if(webView!=null)webView.evaluateJavascript("if(window.gamoraBack){window.gamoraBack();}else if(window.GamoraVetAndroid){GamoraVetAndroid.closeApp();}",null);else super.onBackPressed();}
    @Override protected void onDestroy(){if(webView!=null){webView.destroy();webView=null;}super.onDestroy();}
}
